name: Firebase App Distribution

on:
  push:
    branches:
      - main # Trigger this workflow only on push to main branche

jobs:
  Distribute to Firebase:  
    build:
      runs-on: ubuntu-latest
      steps:
    
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'  # Specify your Ruby version here
          bundler-cache: true
          working-directory: android

      # Step 2: Set up JDK 
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Specify the JDK version here (e.g., '11', '17', etc.)
          distribution: 'adoptopenjdk'  # You can use 'adoptopenjdk', 'zulu', 'openjdk', etc.
      # Step: Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0' # You can specify any stable or specific version of Flutter
     

      # Step 7: Run Fastlane for Firebase App Distribution
      - name: Distribute to Firebase
        run: |
          cd android
          fastlane firebase_app_distribution
        env:
          TOKEN: ${{ secrets.TOKEN }}
