

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :beta do
    sh "flutter clean"
    sh "flutter build apk --flavor development -t lib/main_development.dart"
  
    firebase_app_distribution(
      app: "1:595339030883:android:8a46b7e8dd392d5ea9a356",

      firebase_cli_token: ENV["FIREBASE_TOKEN"],

      android_artifact_path: "../build/app/outputs/apk/development/release/app-development-release.apk",
      testers: "sa.mohammad7567@gmail.com",
      release_notes: "please update to Version 1.4.0+1"
  )
  end



  
end