name: Android Fastlane with Firebase App Distribution Workfloww

on:
  push:
    branches:
      - development

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true
        working-directory: advancedcourse/android
        
    - name: Build and Distribute App
      env:
        firebase_cli_token: ${{ secrets.TOKEN }}
      run: |
        bundle exec fastlane android beta
      working-directory: advancedcourse/android


